// Curated prompt-template seed list.
//
// Prompts are callable units in 2chain: agents discover by capability_text,
// then /call them with `{ vars: { ... } }`. The prompt-template-stub
// substitutes `{{var}}` placeholders and returns `{ rendered: string }`.
//
// Each entry must have a non-empty description and a non-empty template.
// `vars` lists the placeholder keys for documentation; the stub does not
// enforce them (missing vars render as `{{key}}` so callers can iterate).

export interface PromptSeed {
  slug: string;
  description: string;
  template: string;
  vars: string[];
  domain: string;
}

export const PROMPT_SEEDS: PromptSeed[] = [
  {
    slug: 'conventional-commit',
    description:
      'Write a Conventional Commit message (feat/fix/refactor/docs etc.) from a unified diff. Returns a short title plus a 1-3 line body that explains the why, not the what.',
    template:
      'You are writing a Conventional Commit. Read the diff below and produce ONE message.\n\n' +
      'Format: `<type>(<scope>): <imperative title>\\n\\n<body>`\n' +
      'Title <= 72 chars. Body explains the WHY, not the WHAT. No emojis.\n\n' +
      'Diff:\n```\n{{diff}}\n```\n\n' +
      'Commit message:',
    vars: ['diff'],
    domain: 'code',
  },
  {
    slug: 'pr-description',
    description:
      'Generate a pull request description with summary, motivation, and a markdown test-plan checklist from a list of commits and a one-line context.',
    template:
      'Write a PR description.\n\n' +
      'Context: {{context}}\n\n' +
      'Commits:\n{{commits}}\n\n' +
      'Output sections: ## Summary (2-3 bullets), ## Motivation (1 paragraph), ## Test plan (markdown checklist).\n' +
      'No emojis. No "Generated by..." footer.',
    vars: ['context', 'commits'],
    domain: 'code',
  },
  {
    slug: 'bug-report',
    description:
      'Structured bug report template. Captures repro steps, expected vs actual, environment, and severity.',
    template:
      '# Bug: {{title}}\n\n' +
      '**Severity:** {{severity}}\n\n' +
      '## Steps to reproduce\n{{steps}}\n\n' +
      '## Expected\n{{expected}}\n\n' +
      '## Actual\n{{actual}}\n\n' +
      '## Environment\n{{environment}}\n',
    vars: ['title', 'severity', 'steps', 'expected', 'actual', 'environment'],
    domain: 'code',
  },
  {
    slug: 'code-review-checklist',
    description:
      'Senior code reviewer checklist for a diff: correctness, security, performance, readability, tests. Returns a markdown report grouped by severity.',
    template:
      'Act as a senior reviewer. For the diff below, produce a markdown report:\n' +
      '## Blocking, ## High, ## Medium, ## Nits\n' +
      'Each finding: file:line, one-line issue, concrete fix.\n\n' +
      'Focus areas: {{focus}}\n\nDiff:\n```\n{{diff}}\n```',
    vars: ['focus', 'diff'],
    domain: 'code',
  },
  {
    slug: 'user-story-bdd',
    description:
      'Write a BDD user story with Given/When/Then acceptance criteria from a one-line feature ask.',
    template:
      'Write a user story for: {{feature}}\n\n' +
      'Format:\n' +
      'As a {{persona}}\n' +
      'I want to ...\n' +
      'So that ...\n\n' +
      'Acceptance criteria (3-5 items):\n- Given ..., When ..., Then ...\n',
    vars: ['feature', 'persona'],
    domain: 'product',
  },
  {
    slug: 'retro-questions',
    description:
      'Sprint retrospective question set. Tailored prompts for what went well, what to improve, action items.',
    template:
      'You are facilitating a {{teamSize}}-person sprint retro for sprint "{{sprint}}".\n' +
      'Generate 3 questions for "Went well", 3 for "To improve", 2 for "Action items".\n' +
      'Avoid generic prompts. Reference: {{context}}',
    vars: ['teamSize', 'sprint', 'context'],
    domain: 'product',
  },
  {
    slug: 'one-on-one-agenda',
    description:
      'Manager 1:1 agenda template. Sections for status, blockers, growth, feedback. Personalised by role and last-meeting notes.',
    template:
      '1:1 agenda for {{report}} ({{role}}) on {{date}}.\n' +
      'Last 1:1 notes: {{lastNotes}}\n\n' +
      'Sections (5 min each unless noted):\n' +
      '1. Status & wins (3 min)\n' +
      '2. Blockers / asks (5 min)\n' +
      '3. Growth & feedback (10 min)\n' +
      '4. Manager updates (5 min)\n' +
      '5. Open floor\n',
    vars: ['report', 'role', 'date', 'lastNotes'],
    domain: 'management',
  },
  {
    slug: 'linkedin-post',
    description:
      'Draft a LinkedIn post in a builder-engineering voice. No emojis, no hashtag spam, hook-first opening line.',
    template:
      'Write a LinkedIn post.\n' +
      'Topic: {{topic}}\n' +
      'Hook: {{hook}}\n' +
      'Length: {{length}}\n' +
      'Voice: senior engineer, direct, specific. No emojis. No "thrilled to announce". 1-2 hashtags max at the end.',
    vars: ['topic', 'hook', 'length'],
    domain: 'marketing',
  },
  {
    slug: 'x-thread-opener',
    description:
      'Write the first 2 tweets of an X thread that hooks technical builders. Concrete, specific, no throat-clearing.',
    template:
      'Write the first 2 posts of an X thread.\n' +
      'Topic: {{topic}}\n' +
      'Audience: {{audience}}\n' +
      'Constraint: each post <= 280 chars. Post 1 must hook on a concrete number, observation, or contrarian claim. Post 2 sets up the rest of the thread.',
    vars: ['topic', 'audience'],
    domain: 'marketing',
  },
  {
    slug: 'grant-impact-section',
    description:
      'UK research grant Project Impact section template (Innovate UK / DASA / ARIA flavor). 5 paragraphs hitting economic, societal, environmental, capability, and dissemination impact.',
    template:
      'Write the Project Impact section of a {{program}} grant for project "{{project}}".\n' +
      'TRL start: {{trlStart}}, TRL end: {{trlEnd}}.\n' +
      'Sector: {{sector}}.\n\n' +
      '5 paragraphs, ~120 words each:\n' +
      '1. Economic impact (jobs, revenue, cost savings).\n' +
      '2. Societal impact (users helped, reach).\n' +
      '3. Environmental / sustainability.\n' +
      '4. Technical capability gain (UK plc).\n' +
      '5. Dissemination plan (papers, OSS, talks).',
    vars: ['program', 'project', 'trlStart', 'trlEnd', 'sector'],
    domain: 'grants',
  },
  {
    slug: 'design-brief',
    description:
      'Design brief for a UI feature. Captures user goal, success metric, edge cases, and reference inspirations.',
    template:
      'Design brief for {{feature}}.\n\n' +
      '**User goal:** {{userGoal}}\n' +
      '**Primary metric:** {{metric}}\n' +
      '**Edge cases to handle:** {{edges}}\n' +
      '**Reference inspirations:** {{references}}\n' +
      '**Constraints:** {{constraints}}\n',
    vars: ['feature', 'userGoal', 'metric', 'edges', 'references', 'constraints'],
    domain: 'design',
  },
  {
    slug: 'incident-postmortem',
    description:
      'Blameless postmortem template. Timeline, root cause, contributing factors, action items with owners and dates.',
    template:
      '# Postmortem: {{incident}}\n\n' +
      '**Severity:** {{severity}}  **Duration:** {{duration}}  **Owner:** {{owner}}\n\n' +
      '## Summary\n{{summary}}\n\n' +
      '## Timeline (UTC)\n{{timeline}}\n\n' +
      '## Root cause\n{{rootCause}}\n\n' +
      '## Contributing factors\n{{factors}}\n\n' +
      '## Action items\n| Owner | Action | Due |\n|---|---|---|\n{{actionItems}}\n',
    vars: ['incident', 'severity', 'duration', 'owner', 'summary', 'timeline', 'rootCause', 'factors', 'actionItems'],
    domain: 'ops',
  },
];
